# Generated by Django 3.0.8 on 2020-08-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signin_id', models.CharField(db_column='signin_id', max_length=50)),
                ('signin_pw', models.IntegerField(db_column='signin_pw')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
